# StreamingAPIDev @spectest__ (spectest)
twitter:
  screen_name: "spectest__"
  consumer_key: "2paZP9z8K3Rle5ajEMk9VWV5P"
  consumer_secret: "GuK1jkSUvr1xd1T7FTOhnvYtY3f6jAFUXpDVzjJCi8cBtumRsg"
  oauth_token: "4901198484-eLlI7MRaw2bMHZoZaRGjZDlioOvH3p8jGYmkJ7O"
  oauth_token_secret: "SWvBQ87FxlRuiBMmcN7Bsm0alzgkZdDpgPJhPNvy5e0wx"